###########################
#   FILEBEAT CONF
###########################

#================= Filebeat general ===============

logging.level: 'debug'

#================= Filebeat inputs ================

filebeat.inputs:
  - type: 'log'
    enabled: true
    paths:
      - '/mnt/logs/physical-host/**/*.log'
    exclude_files:
      - 'boot.log'
      - 'lynis.log'
    tags:
      - 'system'

  - type: 'docker'
    enabled: true
    combine_partial: true
    containers:
      path: '/mnt/logs/docker'
      stream: 'stdout'
      ids: ['*']
    cri.parse_flags: true
    exclude_files: ['\.gz$']
    ignore_older: '10m'
    json.keys_under_root: true
    json.add_error_key: true
    json.ignore_decoding_error: true
    processors:
      - add_docker_metadata:
          host: 'unix:///var/run/docker.sock'
          match_source_index: 3
    tags:
      - 'docker'

#================Filebeat autodiscover =================

filebeat.autodiscover:
  providers:
    - type: 'docker'
      hints.enabled: true

#================== Filebeat modules ===================

filebeat.modules:

#---------- Modules configuration ----------------------
filebeat.config.modules:
  path: '${path.config}/modules.d/*.yml'
  reload.enabled: false

#---------- Processors configuration ----------------------
processors:
  - add_cloud_metadata: ~

#============ Elasticsearch template setting ============

setup.template.settings:
  index.number_of_shards: 3

#======================== Kibana ========================

setup.kibana:
  host: 'kibana:5601'

setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true
setup.dashboards.retry.interval: "30s"
setup.dashboards.retry.maximum: 5

#=================== Logstash output ====================

#output.logstash:
#  hosts: ['logstash:6000']

#=================== Elasticsearch output ====================
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
