---

auditbeat.modules:

  - module: auditd
    audit_rules: |
      -w /etc/passwd -p wa -k identity
      -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access

  - module: file_integrity
    paths:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    - /etc

output.elasticsearch:
  hosts: ['elasticsearch:9200']

#======================== Kibana ========================

setup.kibana:
  host: 'kibana:5601'

setup.dashboards.enabled: true
setup.dashboards.retry.enabled: true
setup.dashboards.retry.interval: "30s"
setup.dashboards.retry.maximum: 5
